### ISSUE TITLE
عدم کارکرد api

### ISSUE THREAD

**Issue by na3er-faraji** [H320/tricks#4]
سلام. این کد رو من ادد کردم روی پروژه م. 
اون واتر مارک مشکی روی گوگل مپ محو شد
همچنین api direction service در کلاینت و قبل از آپلود روی لوکال هاست درست کار می کنه
اما روی سرور مشتری api direction دیگه کار نمی کنه
آیا این کد فقط واسه حذف واتر مارکه یا باید api هم کار کنه؟

**Comment by H320** [comment]
سلام، من چون بخش مسیریابی رو استفاده نیاز ندارم، برای این بخش تست نکردم، اگر وقت شد روی مسیریابی هم کار میکنم، ولی چیزی فعلا مشخصه مسیریابی گوگل بدون هویت سنجی امکان پذیر نیست، و این اسکریپت هویت سنجی گوگل رو مسدود میکنه
